export const GET_USER_WORDS = 'GET_USER_WORDS';
export const ADD_USER_WORD = 'ADD_USER_WORD';
export const ADD_DELETED_USER_WORD = 'ADD_DELETED_USER_WORD';
export const CHANGE_USER_WORD_ATTRIBUTE = 'CHANGE_USER_WORD_ATTRIBUTE';
export const GET_DELETED_WORDS = 'GET_DELETED_WORDS';
export const GET_DIFFICULT_WORDS = 'GET_DIFFICULT_WORDS';
