export const SET_GAME_STATE = 'SET_GAME_STATE';
export const SET_RIGHT_ANSWER = 'SET_RIGHT_ANSWER';
export const SET_WRONG_ANSWER = 'SET_WRONG_ANSWER';
export const FETCH_WORDS = 'FETCH_WORDS';
export const ERASE_GAME_STATE = 'ERASE_GAME_STATE';
