export const FETCH_TEXTBOOK_WORDS = 'FETCH_TEXTBOOK_WORDS';
export const CHANGE_TRANSLATION = 'CHANGE_TRANSLATION';
export const CHANGE_CONTROLS = 'CHANGE_CONTROLS';

export default FETCH_TEXTBOOK_WORDS;
