export const FETCH_TEXTBOOK_WORDS = 'FETCH_TEXTBOOK_WORDS';
export const TOGGLE_TRANSLATION = 'TOGGLE_TRANSLATION';
export const TOGGLE_CONTROLS = 'TOGGLE_CONTROLS';
export const DELETE_WORD = 'DELETE_WORD';
